# Please Do Not use "latest" until lock files are implemented
# https://github.com/jdx/mise/discussions/6578
# https://github.com/jdx/mise/pull/6231
[tools]
go = "1.25.6"
# make sure go is installed before go tools
"go:golang.org/x/tools/cmd/godoc" = "v0.30.0"
"go:golang.org/x/tools/cmd/goimports" = "v0.30.0"
"ubi:daltonsw/prism" = "1.3.0"
golangci-lint = "2.5.0"
"github:goreleaser/goreleaser-pro" = "2.12.6"
lychee = "0.20.1"
shellcheck = "0.11.0"
shfmt = "3.12.0"
typos = "1.38.1"
yamlfmt = "0.20.0"
terraform = "1.14.5"
gh = "2.86.0"

# go backend is experimental
[settings]
experimental = true
